Test block context methods
concrete-eth/concrete-geth pull request #55
Opened 2024-06-17 21:53 UTC by Iwueseiter

2024-06-19 14:41 UTC, therealbytes commented on concrete/api/environment_test.go
This is in the right direction but the tests need to be more exhaustive. I just merged a fix to main that includes an example test to get you started:

```go
func TestBlockContextMethods(t *testing.T) {
	var (
		r        = require.New(t)
		config   = EnvConfig{IsStatic: true, IsTrusted: false}
		meterGas = true
		gas      = uint64(1e6)
	)

	env, _, _block, _ := NewMockEnvironment(config, meterGas)
	block := _block.(*mockBlockContext)

	t.Run("BlockHash", func(t *testing.T) {
		env.contract.Gas = gas

		var (
			currentBlockNumber = uint64(400)
			lastBlockNumber    = currentBlockNumber - 1
			recentBlockNumber  = currentBlockNumber - 2
			limitBlockNumber   = lastBlockNumber - 255
			limitBlockNumberS1 = limitBlockNumber - 1
			futureBlockNumber  = currentBlockNumber + 1
		)

		block.SetBlockNumber(currentBlockNumber)
		block.SetBlockHash(currentBlockNumber, common.Hash{0x01})
		block.SetBlockHash(lastBlockNumber, common.Hash{0x02})
		block.SetBlockHash(recentBlockNumber, common.Hash{0x03})
		block.SetBlockHash(limitBlockNumber, common.Hash{0x04})
		block.SetBlockHash(limitBlockNumberS1, common.Hash{0x05})
		block.SetBlockHash(futureBlockNumber, common.Hash{0x06})

		r.Equal(common.Hash{}, env.GetBlockHash(currentBlockNumber))
		r.Equal(block.GetHash(lastBlockNumber), env.GetBlockHash(lastBlockNumber))
		r.Equal(block.GetHash(recentBlockNumber), env.GetBlockHash(recentBlockNumber))
		r.Equal(block.GetHash(limitBlockNumber), env.GetBlockHash(limitBlockNumber))
		r.Equal(common.Hash{}, env.GetBlockHash(limitBlockNumberS1))
		r.Equal(common.Hash{}, env.GetBlockHash(futureBlockNumber))

		r.Equal(env.Gas(), gas-6*GasExtStep)
	})

	t.Run("GasLimit", func(t *testing.T) {
		// ...
	})

	// ...

}
```

2024-06-19 14:42 UTC, therealbytes requested changes
This is in the right direction but the tests need to be more exhaustive. I just merged a fix to main that includes an example test to get you started:

```go
func TestBlockContextMethods(t *testing.T) {
	var (
		r        = require.New(t)
		config   = EnvConfig{IsStatic: true, IsTrusted: false}
		meterGas = true
		gas      = uint64(1e6)
	)

	env, _, _block, _ := NewMockEnvironment(config, meterGas)
	block := _block.(*mockBlockContext)

	t.Run("BlockHash", func(t *testing.T) {
		env.contract.Gas = gas

		var (
			currentBlockNumber = uint64(400)
			lastBlockNumber    = currentBlockNumber - 1
			recentBlockNumber  = currentBlockNumber - 2
			limitBlockNumber   = lastBlockNumber - 255
			limitBlockNumberS1 = limitBlockNumber - 1
			futureBlockNumber  = currentBlockNumber + 1
		)

		block.SetBlockNumber(currentBlockNumber)
		block.SetBlockHash(currentBlockNumber, common.Hash{0x01})
		block.SetBlockHash(lastBlockNumber, common.Hash{0x02})
		block.SetBlockHash(recentBlockNumber, common.Hash{0x03})
		block.SetBlockHash(limitBlockNumber, common.Hash{0x04})
		block.SetBlockHash(limitBlockNumberS1, common.Hash{0x05})
		block.SetBlockHash(futureBlockNumber, common.Hash{0x06})

		r.Equal(common.Hash{}, env.GetBlockHash(currentBlockNumber))
		r.Equal(block.GetHash(lastBlockNumber), env.GetBlockHash(lastBlockNumber))
		r.Equal(block.GetHash(recentBlockNumber), env.GetBlockHash(recentBlockNumber))
		r.Equal(block.GetHash(limitBlockNumber), env.GetBlockHash(limitBlockNumber))
		r.Equal(common.Hash{}, env.GetBlockHash(limitBlockNumberS1))
		r.Equal(common.Hash{}, env.GetBlockHash(futureBlockNumber))

		r.Equal(env.Gas(), gas-6*GasExtStep)
	})

	t.Run("GasLimit", func(t *testing.T) {
		// ...
	})

	// ...

}
```

2024-06-19 14:43 UTC, therealbytes commented
Note you will need to rebase on main for your tests to pass.

2024-06-19 14:47 UTC, Iwueseiter commented
@therealbytes I will work on it.

2024-06-21 15:10 UTC, therealbytes commented
Hey, any progress here?

2024-06-21 21:02 UTC, therealbytes requested changes
This is still missing some of the changes I requested. Look at my previous review and the examples provided.

2024-06-24 06:56 UTC, Iwueseiter commented
I'm working on it. I will update the PR today.

2024-06-24 14:24 UTC, therealbytes requested changes
Looking good. I think you accidentally deleted `TestCallMethods` while resolving merge conflicts.
- `TestBlockOps_Minimal` can be deleted
- `TestCallMethods` should NOT be deleted

2024-06-24 17:47 UTC, Iwueseiter commented
@therealbytes I will rectify that.

2024-06-25 14:58 UTC, therealbytes requested changes

2024-06-25 14:58 UTC, therealbytes commented on concrete/api/environment_test.go
>  package api
Needs an empty line before this line (under `// issues.`),

2024-06-25 14:58 UTC, therealbytes commented on concrete/api/environment_test.go
>  func TestCallMethods(t *testing.T) {
Needs an empty line before this line (under `}`).

2024-06-25 16:12 UTC, Iwueseiter commented
@therealbytes  Done

2024-06-25 16:27 UTC, therealbytes approved these changes

2024-06-25 16:27 UTC, merged