Test state methods in Concrete environment
concrete-eth/concrete-geth pull request #67
Opened 2024-07-27 10:54 UTC by fishonamos

Closes #34

2024-07-28 15:12 UTC, therealbytes requested changes

2024-07-28 15:12 UTC, therealbytes commented on concrete/api/environment_test.go
> +func TestEnvironmentStateMethods(t *testing.T) {
Can you rename this to TestStateMethods and move it to the bottom of the file?

2024-07-28 15:12 UTC, therealbytes commented on concrete/api/environment_test.go
> +	env, statedb, _, _ := NewMockEnvironment(config, meterGas)
Rebase on main and use the new version of NewMockEnvironment.

2024-07-28 15:12 UTC, therealbytes commented on concrete/api/environment_test.go
> +	t.Run("StorageLoad and StorageStore", func(t *testing.T) {
Rename this to "Storage".

2024-07-28 15:12 UTC, therealbytes commented on concrete/api/environment_test.go
> +
Check that the log has been added to the StateDB.

2024-08-03 05:09 UTC, therealbytes requested changes
Running the tests results in a panic.

Also, I don't see why the changes to mock statedb and env are necessary. Could you explain?

2024-08-03 06:49 UTC, fishonamos commented
> Running the tests results in a panic.
> 
> Also, I don't see why the changes to mock statedb and env are necessary. Could you explain?

The update you made to mock was not compatible  with existing mockStateDB and the interface. and a lot of merge conflicts when i rebased. So I had to manually fix them to fit the existing state. Let me try to do an a mirror implementation on another branch.  Will post a screenshot of the tests status.

2024-08-05 23:54 UTC, fishonamos commented
All the tests are passing except GetCodeSize & GetExternalCodeSize. What could be the reason? Can you check please?

I commented them.

2024-08-06 16:32 UTC, therealbytes commented
I just merged a PR that should fix it. Try rebasing.

That said, I still don't see why any of the changes in interface_go.go and mock.go are necessary.

You can use the existing mocks like this:

```golang
func TestStateMethods(t *testing.T) {
	r := require.New(t)
	config := EnvConfig{IsStatic: false, IsTrusted: false}
	meterGas := true

	env, statedb, _, _ := NewMockEnvironment(WithConfig(config), WithMeterGas(meterGas))
	env.contract.Gas = uint64(1e6)

	t.Run("Storage", func(t *testing.T) {
		key := common.HexToHash("0x01")
		value := common.HexToHash("0x02")
		env.StorageStore(key, value)
		loadedValue := env.StorageLoad(key)
		r.Equal(value, loadedValue)
		storedValue := statedb.GetState(env.Contract().Address, key)
		r.Equal(value, storedValue)
	})

	t.Run("Log", func(t *testing.T) {
		topics := []common.Hash{common.HexToHash("0x01"), common.HexToHash("0x02")}
		data := []byte("log data")
		env.Log(topics, data)
		log := &types.Log{
			Address: env.Contract().Address,
			Topics:  topics,
			Data:    data,
		}
		logs := statedb.(*state.StateDB).Logs()
		r.Len(logs, 1)
		r.Equal(log, logs[0])
	})

	t.Run("GetCode", func(t *testing.T) {
		code := []byte{0x60, 0x60, 0x60}
		statedb.(*state.StateDB).SetCode(env.Contract().Address, code)
		loadedCode := env.GetCode()
		r.Equal(code, loadedCode)
	})

	t.Run("GetCodeSize", func(t *testing.T) {
		code := []byte{0x60, 0x60, 0x60}
		statedb.(*state.StateDB).SetCode(env.Contract().Address, code)
		loadedCodeSize := env.GetCodeSize()
		r.Equal(len(code), loadedCodeSize)
	})

	t.Run("GetExternalBalance", func(t *testing.T) {
		address := common.HexToAddress("0x12345")
		balance := uint256.NewInt(5000)
		statedb.(*state.StateDB).SetBalance(address, balance)
		loadedBalance := env.GetExternalBalance(address)
		r.Equal(balance, loadedBalance)
	})

	t.Run("GetExternalCode", func(t *testing.T) {
		address := common.HexToAddress("0x12345")
		code := []byte{0x61, 0x61, 0x61, 0x61}
		statedb.(*state.StateDB).SetCode(address, code)
		loadedCode := env.GetExternalCode(address)
		r.Equal(code, loadedCode)
	})

	t.Run("GetExternalCodeSize", func(t *testing.T) {
		address := common.HexToAddress("0x12345")
		code := []byte{0x61, 0x61, 0x61, 0x61}
		statedb.(*state.StateDB).SetCode(address, code)
		loadedCodeSize := env.GetExternalCodeSize(address)
		r.Equal(len(code), loadedCodeSize)
	})

	t.Run("GetExternalCodeHash", func(t *testing.T) {
		address := common.HexToAddress("0x12345")
		code := []byte{0x61, 0x61, 0x61, 0x61}
		statedb.(*state.StateDB).SetCode(address, code)
		loadedCodeHash := env.GetExternalCodeHash(address)
		r.Equal(crypto.Keccak256Hash(code), loadedCodeHash)
	})
}
```

The only things missing here would be checking the gas costs are correct.

2024-08-06 16:43 UTC, fishonamos commented
Alright. Checking

On Tue, 6 Aug 2024, 17:33 bytes, ***@***.***> wrote:

> I just merged a PR that should fix it. Try rebasing.
>
> That said, I still don't see why any of the changes in interface_go.go and
> mock.go are necessary.
>
> You can use the existing mocks like this:
>
> func TestStateMethods(t *testing.T) {
> 	r := require.New(t)
> 	config := EnvConfig{IsStatic: false, IsTrusted: false}
> 	meterGas := true
>
> 	env, statedb, _, _ := NewMockEnvironment(WithConfig(config), WithMeterGas(meterGas))
> 	env.contract.Gas = uint64(1e6)
>
> 	t.Run("Storage", func(t *testing.T) {
> 		key := common.HexToHash("0x01")
> 		value := common.HexToHash("0x02")
> 		env.StorageStore(key, value)
> 		loadedValue := env.StorageLoad(key)
> 		r.Equal(value, loadedValue)
> 		storedValue := statedb.GetState(env.Contract().Address, key)
> 		r.Equal(value, storedValue)
> 	})
>
> 	t.Run("Log", func(t *testing.T) {
> 		topics := []common.Hash{common.HexToHash("0x01"), common.HexToHash("0x02")}
> 		data := []byte("log data")
> 		env.Log(topics, data)
> 		log := &types.Log{
> 			Address: env.Contract().Address,
> 			Topics:  topics,
> 			Data:    data,
> 		}
> 		logs := statedb.(*state.StateDB).Logs()
> 		r.Len(logs, 1)
> 		r.Equal(log, logs[0])
> 	})
>
> 	t.Run("GetCode", func(t *testing.T) {
> 		code := []byte{0x60, 0x60, 0x60}
> 		statedb.(*state.StateDB).SetCode(env.Contract().Address, code)
> 		loadedCode := env.GetCode()
> 		r.Equal(code, loadedCode)
> 	})
>
> 	t.Run("GetCodeSize", func(t *testing.T) {
> 		code := []byte{0x60, 0x60, 0x60}
> 		statedb.(*state.StateDB).SetCode(env.Contract().Address, code)
> 		loadedCodeSize := env.GetCodeSize()
> 		r.Equal(len(code), loadedCodeSize)
> 	})
>
> 	t.Run("GetExternalBalance", func(t *testing.T) {
> 		address := common.HexToAddress("0x12345")
> 		balance := uint256.NewInt(5000)
> 		statedb.(*state.StateDB).SetBalance(address, balance)
> 		loadedBalance := env.GetExternalBalance(address)
> 		r.Equal(balance, loadedBalance)
> 	})
>
> 	t.Run("GetExternalCode", func(t *testing.T) {
> 		address := common.HexToAddress("0x12345")
> 		code := []byte{0x61, 0x61, 0x61, 0x61}
> 		statedb.(*state.StateDB).SetCode(address, code)
> 		loadedCode := env.GetExternalCode(address)
> 		r.Equal(code, loadedCode)
> 	})
>
> 	t.Run("GetExternalCodeSize", func(t *testing.T) {
> 		address := common.HexToAddress("0x12345")
> 		code := []byte{0x61, 0x61, 0x61, 0x61}
> 		statedb.(*state.StateDB).SetCode(address, code)
> 		loadedCodeSize := env.GetExternalCodeSize(address)
> 		r.Equal(len(code), loadedCodeSize)
> 	})
>
> 	t.Run("GetExternalCodeHash", func(t *testing.T) {
> 		address := common.HexToAddress("0x12345")
> 		code := []byte{0x61, 0x61, 0x61, 0x61}
> 		statedb.(*state.StateDB).SetCode(address, code)
> 		loadedCodeHash := env.GetExternalCodeHash(address)
> 		r.Equal(crypto.Keccak256Hash(code), loadedCodeHash)
> 	})
> }
>
> The only things missing here would be checking the gas costs are correct.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/concrete-eth/concrete-geth/pull/67#issuecomment-2271695461>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKOUVHKGLXBTHZ46XLURKSTZQD3FBAVCNFSM6AAAAABLRY7EACVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENZRGY4TKNBWGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-06 17:14 UTC, fishonamos commented
Nice @therealbytes . The update to the env fixed the tests!

2024-08-06 17:46 UTC, fishonamos commented
too many conflicts on this branch. Requesting to close in favour of #73 . I will leave it open for now as reference.

2024-08-07 07:32 UTC, closed without merging